### ISSUE TITLE
Don't include fullcalendar.print in CSS manifest

### ISSUE THREAD

**Issue by rzane** [bokmann/fullcalendar-rails#11]
In README.md, it says to do the following:

> At this point, the files from the fullcalendar project are in your asset pipeline's path... all you have to do is require them in the appropriate places.  For instance, in your application.css.scss:

```
*= require fullcalendar
*= require fullcalendar.print
```

If you follow these instructions, you might have a difficult time changing the colors for events, because fullcalendar.print overrides the styles because it includes the following lines:

``` css
.fc-event {
    background: #fff !important;
    color: #000 !important;
}
```

I think the README.md should instruct users to only include `*= require fullcalendar` in the application.css.scss, and then in their layout file, do the following:

``` erb
<%= stylesheet_link_tag "fullcalendar.print", :media => "print" %>
```

**Comment by abulasar4all** [comment]
Thans a lot this help. 5 mins before i had spend 1 hour in finding out the reason why styling is not getting applied. Then luckily i got this thread. +1:

**Comment by elmoaaron** [comment]
I had to do this to make print style work
``
@media print {
    @import 'fullcalendar.print';
}
``
even when I used this line in my layout
``
<%= stylesheet_link_tag "fullcalendar.print", :media => "print" %>
``
