### ISSUE TITLE
Version 2.2.5 error

### ISSUE THREAD

**Issue by davidreghay** [bokmann/fullcalendar-rails#38]
First of all, I can't tell you how grateful I am to have this gem!

On to the issue.  In the latest version I've discovered that events rendered a day prior to their actual <code>start</code>.

**Comment by davidreghay** [comment]
Also, the <code>popover</code> generated by an <code>eventLimitClick</code> is now empty.

By the way, although it's <em>certainly</em> not a bug, I don't like the fact that it the <code>title</code> now is (<code>current_month - next_month</code>).  I think that can be confusing and that the old format was clearer.

**Comment by gr8bit** [comment]
Hi David! This gem is only a package containing FullCalendar; we're not the authors of FullCalendar itself. You'll find the correct project here: https://github.com/arshaw/fullcalendar
Please redirect your issue and the thanks (!) to Adam Shaw, the author of FullCalendar. :) Thank you!

**Comment by davidreghay** [comment]
Mysteriously enough, when I manually add the assets from https://github.com/arshaw/fullcalendar there isn't any problem.  It specifically happens when loading them through the fullcalendar-rails gem (and only the latest one!)  Even weirder, when I compare the contents of the respective fullcalendar.js files they are identical...  And that's a shame, because I've really enjoyed being able to use this gem instead of loading scripts manually.

In light of this, I doubt that redirecting the issue to Adam Shaw is the right move here, as the bug doesn't seem to appear when fullcalendar is manually loaded.

Can anyone verify that this is the case?  I suspect that you'll find the same to be true if you bundle update on any apps that make use of this gem vs loading the fullcalendar.js file manually.

**Comment by gr8bit** [comment]
Oh I'm sorry, but you forgot to mention that the bugs you're experiencing occur only when you use this gem in the first place, so I thought you are filing a bug report for FullCalendar itself! :)
I will look into this issue. My guess is that it's not related to fullcalendar.js but to one of the required gems (momentjs or jquery). Can you please check which versions of these reqirements are bundled in your app?

**Comment by davidreghay** [comment]
Sorry for the late response on this.  Busy weekend.

Just found the answer!  Your suspicion was correct and the issue was resulting somehow from the version of momentjs.  I'm not sure exactly how or why, but momentjs v 2.8.3 does not play nicely with fullcalendar v 2.2.5.  I think it has to do somehow with the fact that only in v 2.8.4 was added `Support 24:00:00.000 to mean next day, at midnight.`

Presumably up to fullcalendar v 2.2.3 this was somehow compensated for in event rendering but in v 2.2.5 it is deemed no longer necessary and so this discrepancy arose.

**Comment by gr8bit** [comment]
Ah, thank you! I will increase the required gem version for momentjs. :)

**Comment by gr8bit** [comment]
Uh, I can't... Its still at 2.8.3 but I contacted @derekprior and asked him to update it.

**Comment by davidreghay** [comment]
I noticed this also.  That's life, I suppose.  I was going to update it myself and make a pull request but I saw that @dbackowski has already done so.

Thanks for the help!

**Comment by derekprior** [comment]
Update momentjs-rails to 2.8.4 and also 2.9.0

**Comment by gr8bit** [comment]
Thank you Derek! I will push the new version in a minute.
