### ISSUE TITLE
Fullcalendar doesnt allow including application.js and application.css.scss tags in application.html.erb rails 

### ISSUE THREAD

**Issue by boyfunky** [bokmann/fullcalendar-rails#41]
http://stackoverflow.com/questions/28198933/fullcalendar-header-toolbar-buttons-not-showing-when-application-css-and-javascr

Based on the question posted here in Stackoverflow. I followed the same installation and implementation for fullcalendar but it doesnt. It shows the calendar but doesnt show the buttons (prev, next, day, week, month) etc..

**Comment by gr8bit** [comment]
Acknowledged, but unfortunately I'll need some days to evaluate that. Is downgrading an option in the meanwhile?
You're also very welcome to collect hints to where the actual problem is within the gem, because its actually a very simple packaging...

Thank you!

**Comment by boyfunky** [comment]
Downgrading is an option but using rails 4 is a must. When i run the fullcalendar assets it runs properly but it is on rails 3 but not on rails 4.

**Comment by Inveera123** [comment]
i am run the fullcalendar-rails on rails 4 but calendar header not display.

**Comment by gr8bit** [comment]
Just tu be sure it isn't fixed yet please check out the new version @boyfunky

**Comment by hav3loc** [comment]
I'm afraid issue still isn't fixed, only title can be displayed in the header. Any ideas how to bypass this problem for now? Any help would be very appraciated.

**Comment by gr8bit** [comment]
I still don't have enough time to dig into that error, a pull request from someone who has and sorted it out would be much appreciated!

**Comment by pternol** [comment]
Looks like it's an bug with the assets pipeline in rails 4, didn't test it with rails 3 but fullcalendar versions prior to 2.x do actually work. I tried to locate the problem but I can't even see the problem. The header  icons are there in html, so I think it's an stylesheet issue. Maybe **some** styles are overwritten by some stuff we all have in our pipeline (e.g. Bootstrap?).  Would love some brain storming on this!

**Comment by gr8bit** [comment]
Strange... Did you set up a fresh project to test this? If so, could you share the repo?

**Comment by pternol** [comment]
Actually I did set up a fresh project but I can't share it with you. Sorry
