### ISSUE TITLE
Upgrade Fullcallendar to 2.3.0

### ISSUE THREAD

**Issue by janko-m** [bokmann/fullcalendar-rails#42]
Thank you for maintaining this gem, I love when I can just include a gem rather than commit a JS file in the version control.

There has been an [important bugfix](https://code.google.com/p/fullcalendar/issues/detail?id=2433) which we need in our application. So it would be great to see this updated to the latest version :)

**Comment by Zofz** [comment]
Would love it too! 😄

**Comment by bokmann** [comment]
I'll gladly accept a pull request...

**Comment by gr8bit** [comment]
Merged pul request from @Zofz
