### ISSUE TITLE
Testing helpers 

### ISSUE THREAD

**Issue by davidwessman** [bokmann/fullcalendar-rails#44]
Worked a bit with some testing of my modules which implements Fullcalendar and I thought it would be nice to add some testhelpers to the gem.
Would you like this? Or do you just want to put the JS in the pipeline?

Cheers, David

**Comment by gr8bit** [comment]
Hi David!

What do you test with your helpers? If they relate directly to functionality of fullcalendar itself, I think they should be contributed to fullcalendar itself, not to this gem. If they relate to functionality introduced by this gem-repackaging, then I'd love to have a look at them. :)

Cheers,
Niklas
