### ISSUE TITLE
Upgrade Fullcallendar to 2.4.0

### ISSUE THREAD

**Issue by maxime-lenne** [bokmann/fullcalendar-rails#48]
Hi,

I create a pull request to upgrade to FullCalendar 2.4.0

**Comment by kschutt** [comment]
+1

**Comment by gr8bit** [comment]
@maxime-lenne did you use the original full calendar-release without reformatting it? it shows many whitespace-diffs, that's why I ask. We only intend to repackage the raw, unedited fullcalendar-releases.

**Comment by denisemauldin** [comment]
+1

**Comment by gr8bit** [comment]
Done and pushed to rubygems. I need to update jquery and jquery-ui dependencies it seems though... Please let me know if you have problems with the current version!
