### ISSUE TITLE
Can't find how to make allDaySlot selectable

### ISSUE THREAD

**Issue by davidgeismar** [bokmann/fullcalendar-rails#51]
Based on this question in stackoverflow
http://stackoverflow.com/questions/32993326/impossible-to-select-all-day-slots-with-fullcalendar
I can't figure out how to make the allDaySlot selectable. 
Is it also possible to set up fullcalendar so that when the user selects the allDaySlot, the whole row concerning that day appears as selected ?

**Comment by gr8bit** [comment]
Please note this is not the fullcalendar repository. This is just a project re-packaging the fullcalendar code for use in the Ruby on Rails asset pipeline. You might want to ask your question/submit your issue in the fullcalendar repo here:
https://github.com/fullcalendar/fullcalendar
