### ISSUE TITLE
Does this gem work well with Rails 4x?

### ISSUE THREAD

**Issue by wenwei63029869** [bokmann/fullcalendar-rails#56]

**Comment by davidwessman** [comment]
It works perfect for me on 4.2.5

Any specific issue?

**Comment by wenwei63029869** [comment]
Thank you! Not yet. I am still deciding which calendar gem I should use.

**Comment by davidwessman** [comment]
A question like this would belong in a forum such as StackOverflow unless you have any actual issues with this gem.

@gr8bit you should close this.

**Comment by gr8bit** [comment]
Thanks for the reply David, closing this. :)
