### ISSUE TITLE
Does fullcalendar have an option for scheduler?

### ISSUE THREAD

**Issue by sunsheeppoplar** [bokmann/fullcalendar-rails#59]
I'm trying to figure out what the difference between the normal fullcalendar and its scheduler premium add-ons as I'll need it in a new rails application I'm working on. Does this gem provide the option of scheduler or is that something I would need to manually deal with? Any help is much appreciated!

**Comment by davidwessman** [comment]
The gem does not include the Scheduler add-on or any options for it.
But this is simply a wrapper for the `fullcalendar.js` and you might be able to combine the two, but you would need to add `scheduler.css` and `scheduler.js` on your own.

(Correct me if I'm wrong @gr8bit @bokmann)

**Comment by sunsheeppoplar** [comment]
Thanks, @davidwessman. I appreciate it!
