### ISSUE TITLE
Bundler Not Defaulting to Newest Version (2.7.2)

### ISSUE THREAD

**Issue by sunsheeppoplar** [bokmann/fullcalendar-rails#60]
I tried bundle updating just now, but I'm guessing it hasn't been changed?

**Comment by sunsheeppoplar** [comment]
https://rubygems.org/gems/fullcalendar-rails/versions

Am I doing something wrong?

**Comment by sunsheeppoplar** [comment]
Ah, sorry. I didn't realize that I could just point at the repository directly. In any case, I guess most of my issues are arising from Scheduler conflicts. Are there any thoughts on having an option to install Scheduler? I wouldn't mind making a pull request if there were.

**Comment by davidwessman** [comment]
@gr8bit This can be closed now.

But I guess Scheduler integration should be an issue of its own.
