### ISSUE TITLE
FullCanlendar don't working for Rails 4

### ISSUE THREAD

**Issue by OceanDemy** [bokmann/fullcalendar-rails#64]
I to do all task as guide.

I use Rails 4.

Installation

In order to install the fullcalendar-rails gem and get FullCalendar working within your application, do the following steps:

Add to gemfile

gem 'fullcalendar-rails'
gem 'momentjs-rails'
Bundle install and restart rails server.

Add to application.js

//= require moment 
//= require fullcalendar

$('#calendar').fullCalendar({});
Add to application.css

*= require fullcalendar
In view, include the following html:

<div id="calendar"></div>

# ## **But, it does not show calendar in views.**

**Comment by davidwessman** [comment]
Hello @OceanDemy 
What kind of event source do you use? A JSON-feed?

See more at the Fullcalendar docs:
http://fullcalendar.io/docs/event_data/

**Comment by vital-edu** [comment]
It is not workink with me too. The calendar does not shows up.
There is no error in the JavaScript console.

I am using Rails 5 and scss.

**Comment by vital-edu** [comment]
It is not a issue. The only thing that it is needed it is  call the javascript function when the document it is ready.

It would be nice has that in the README.

$(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
        // put your options and callbacks here
    })

});

Font: http://stackoverflow.com/a/19121503

**Comment by benjam1n** [comment]
For rails 5 this seems to be a solution:

```
$(document).on('turbolinks:load', function() {
    // fullCalendar goes here
}
```

**Comment by HectorMF** [comment]
I was having the same problem with rails 5.  Was definitely a turbolinks problem, I added the following code to the bottom of application.js and it seemed to solve all my problems.  

`document.addEventListener("turbolinks:load", function() {
  $('#calendar').fullCalendar({});
})`

**Comment by davidwessman** [comment]
@benjam1n @HectorMF 
I copied in my answer from: #78 

---
You have to load your calendars in a good manner, with Turbolinks 5 you need to remove Fullcalendar from a `before_cache` tag.

Example:
```
function eventCalendar() {
  return $('#event_calendar').fullCalendar({ ***config***});
};
function clearCalendar() {
  $('#event_calendar').fullCalendar('delete'); // In case delete doesn't work.
  $('#event_calendar').html('');
};
$(document).on('turbolinks:load', eventCalendar);
$(document).on('turbolinks:before-cache', clearCalendar)
```

Link to Turbolinks regarding idempotent scripts:
https://github.com/turbolinks/turbolinks#making-transformations-idempotent

**Comment by gr8bit** [comment]
You're all more than welcome to put this into the README 👍 :)

**Comment by gr8bit** [comment]
Ok, I did it. ;) Thanks for finding out!
