### ISSUE TITLE
Breaks the pagination links of Kaminari

### ISSUE THREAD

**Issue by ajeferson** [bokmann/fullcalendar-rails#65]
Hi there, 

I'm using fullcalendar-rails gem and also the [kaminari](https://github.com/amatsuda/kaminari) gem for pagination. The pagination does not happen if I just include full calendar on my application.js file.

**Comment by davidwessman** [comment]
Hello @ajeferson 
Do you get any errors in your browser console or such?
Can you please describe some more what is happening?

However this is only a packaging of the [Fullcalendar JS by Arshaw](http://fullcalendar.io)
