### ISSUE TITLE
Refreshing page comes to present date

### ISSUE THREAD

**Issue by vuppalasrinivas** [bokmann/fullcalendar-rails#66]
Calendar is showing current date after refreshing the page. For example if i am in month of September after refreshing the page it is showing current month august. I want to show same month events where i refresh the page.

**Comment by davidwessman** [comment]
This is the way the javascript-framework works.
Check in with fullcalendar.io and see if you can somehow hook into the events to change the url.

This gem is only a packaging of the JS.
