### ISSUE TITLE
doesn't work in procution enviroment by heroku(rails)

### ISSUE THREAD

**Issue by MoltndarKen** [bokmann/fullcalendar-rails#68]
doesn't work because of 'http' protocol .
 <script src='http//fullcalendar.io/js/fullcalendar-2.1.1/lib/moment.min.js'></script>
  <script src='http//fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery.min.js'></script>
  <script src="http//fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery-ui.custom.min.js"></script>
  <script src='http//fullcalendar.io/js/fullcalendar-2.1.1/fullcalendar.min.js'></script>

**Comment by MoltndarKen** [comment]
May you ready for https protocol script?

**Comment by davidwessman** [comment]
Can you show some log? Where is the problem?
I use this frequently on https

**Comment by pmargreff** [comment]
@MoltndarKen it's strange, works well on heroku for me, talk more about the problem.

**Comment by MoltndarKen** [comment]
@davidwessman  @pmargreff  I'm very sorry for replying too late.  It was resolved. It was  my  fault because of not dealing with jquery event, sorry.  Fullcalender is now very usefull for us. Thanks a lot.
