### ISSUE TITLE
Upgrade to use the latest version

### ISSUE THREAD

**Issue by brendon** [bokmann/fullcalendar-rails#69]
Hi there, it looks like this gem is a bit behind as far as fullcalendar goes. Would you be interested in releasing a version with the latest version of fullcalendar?

**Comment by davidwessman** [comment]
If you can provide a PR it would be great 😄

**Comment by brendon** [comment]
Haha, I knew that would probably be your answer. I'll see what I can come up with.

**Comment by brendon** [comment]
There you go. Let me know if you need any changes. I'm also doing a PR for momentjs.

**Comment by gr8bit** [comment]
Thanks, all merged and pushed to rubygems :)
