### ISSUE TITLE
Fullcalendar JS initialization

### ISSUE THREAD

**Issue by sgelliott** [bokmann/fullcalendar-rails#71]
Currently you're linking to http://blog.crowdint.com/2014/02/18/fancy-calendars-for-your-web-application-with-fullcalendar.html as a reference. Following instructions I wasn't able to get a working sample. The link mentions the following....

```
$('#calendar').fullCalendar(
    events: '/events.json'
);
```

This does not work for me. Instead, I wrapped the events parameter in an object like this...

```
$('#calendar').fullCalendar({
    events: '/events.json'
});
```

The 2nd example worked. The former threw an error. Am I missing something or are things maybe not up to date?

**Comment by gr8bit** [comment]
I think it may be outdated. The reference linked to exposes its from Februrary 2014, so there may be quite some changes. Do you have a better source for usage examples? Or maybe you could help out with some usage documentation by yourself? PRs welcome :)

**Comment by gr8bit** [comment]
I will hint this in the documentation. Thank you!
