### ISSUE TITLE
Documentation for styling

### ISSUE THREAD

**Issue by sgelliott** [bokmann/fullcalendar-rails#72]
Is it helpful to offer styling guidance? So people can adjust SCSS/CSS to customize their implementations? Happy help with such documentation.

**Comment by gr8bit** [comment]
I think that would be related to the original FullCalendar, wouldn't it? Or do I get you wrong?

**Comment by benjam1n** [comment]
Yeah, that's related to original FullCalendar. @pandahug Just take [their default CSS](https://github.com/fullcalendar/fullcalendar/blob/master/src/common/common.css) and adjust whatever you need.
