### ISSUE TITLE
Update the JS library

### ISSUE THREAD

**Issue by zedtux** [bokmann/fullcalendar-rails#77]
The current version of fullcalendar is 3.2.0 while this gem is packing the 2.8.

**Comment by davidwessman** [comment]
https://rubygems.org/gems/fullcalendar-rails/versions/3.2.0.0

**Comment by zedtux** [comment]
So push the tags 😅 in this repository. I just double checked and I can see I have the version 3.2.0 in my project.

Thank you @davidwessman.
