### ISSUE TITLE
Different calendars for different events places

### ISSUE THREAD

**Issue by knzudgt** [bokmann/fullcalendar-rails#83]
I read the useful and well written tutorial by Fernando Perales, which is linked in the readme.md file.
Since I would like to use `fullcalendar-rails` for my application, and I am new with `json`, I would like to ask some questions.

My `Event` model has a `place` attribute, which is the place where the event is held.
My goal is to have different calendars for different places, because each place has its own events.
Would it work if, after defining a `search` method in the `Event` model, I defined the instance variable `@events` used by the `index.json.builder` file as `@events = Event.search(params[:search])` ?

Is the index page of the RESTful Events resource the right place to define `@events`?
What events will I see if I go to: `localhost:3000/events.json` or to: `localhost:3000/events`?

Since the `show` action of the RESTful Events resource corresponds to the url `/events/1` for the event with `id=1`, I wonder if I will be routed correctly using for each event in the `index.json.builder` file the html format which generates a url such as `/events/1.html`. In fact, as common rails practice, I would insert the partial for the generic event in `app/views/events/show.html.erb`

Lastly: my users choose the day of the event with jQuery date picker, so the attribute `event_date` will be saved as a string with format `"yy-mm-dd"`: how can I set json `start` and `end`? Are they necessary?

**Comment by davidwessman** [comment]
I think this would be much better at https://stackoverflow.com/, write your question there and link it in a comment. I can try to respond there.

**Comment by knzudgt** [comment]
Thanks @davidwessman . I wrote [my question at stackoverflow](https://stackoverflow.com/q/45368853/5078888).

**Comment by davidwessman** [comment]
@knzudgt I wrote together an answer now, please close this issue and continue the discussion there :)
