### ISSUE TITLE
Different calendars for different places not working

### ISSUE THREAD

**Issue by knzudgt** [bokmann/fullcalendar-rails#84]
I recently opened a similar issue and got help from @davidwessman.
See my [question](https://stackoverflow.com/questions/45368853/fullcalendar-rails-different-calendars-for-different-events-places/45398855#45398855) at stackoverflow.

My application is in Rails 5.0.0.1, therefore I have to use `form_tag` in place of the `form_with` suggested by @davidwessman in his answer and in [his gist](https://gist.github.com/davidwessman/7597e3eea4e71238d7f71a74928e64bd).

Considering the scope suggested: `scope(:place, (search), -> { where('place LIKE ?', "%#{search}%") })`, I had to add a comma after (search), otherwise Atom's Linter would raise an error. Also I could not use it in the event model, because I receive the following error:

    undefined local variable or method `search' for #<Class:0x007f6979f9c128>

Therefore, I changed the scope with the method below:

    def self.place(search)
      where("place ILIKE ?", "#{search}")
    end

I made two attempts, one defining` @events` in the index action of the events controller, the other in a custom feed action as suggested by @davidwessman, however they both fail: fullcalendar does not show up.

I created two gists with my two attempts in case someone of you want to check my code: [gist1](https://gist.github.com/knzudgt/a5cd4c29b97919a96ff3d70bd6677f5a) and [gist2](https://gist.github.com/knzudgt/c89547310500529d9caf2887fb724ddf).

My server log is below:

    Started GET "/events?utf8=%E2%9C%93&place=london&commit=Search" for 127.0.0.1 at 2017-08-13 16:28:10 +0200
    Processing by EventsController#index as JS
      Parameters: {"utf8"=>"✓", "place"=>"london", "commit"=>"Search"}
      User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
      Rendering events/index.html.erb within layouts/application
      Rendered events/index.html.erb within layouts/application (1.0ms)
      Rendered layouts/_shim.html.erb (0.3ms)
      Rendered layouts/_header.html.erb (2.1ms)
      Rendered layouts/_footer.html.erb (0.3ms)
    Completed 200 OK in 88ms (Views: 83.8ms | ActiveRecord: 0.2ms)

NOTE: one strange thing is that when I go to the event index page the input is pre-filled with the following content: `{:id=>"place-field", :placeholder=>"Search events"}`

**Comment by davidwessman** [comment]
Can you share an application so we can see where things go wrong?

**Comment by davidwessman** [comment]
I realised my syntax on the scope was wrong:
`scope(:place, (search)-> { where('place LIKE ?', "%#{search}%") })` should be 

`scope(:place, ->(search) { where('place LIKE ?', "%#{search}%") })`

I think your error is not with the event source, but with your loading and execution of JS.

Would be great with an example application - and I might find what is wrong. @knzudgt

**Comment by knzudgt** [comment]
@davidwessman I have an application at Cloud9 that I use for testing purposes. Since the workspace is private I can invite you as a member or I can change the workspace visibility from private to public and, if you want, you and others can have a look there. _I still have to create the Event model at Cloud9 though_. Otherwise I accept suggestions for alternative solutions. Pushing the Cloud9 application at Github is another solution, I suppose.

**Comment by davidwessman** [comment]
Please make it public if you want. You can send the link to david@wessman.co if you do not want to post it here.

**Comment by knzudgt** [comment]
@davidwessman Here is the [url of my rails-tests](https://ide.c9.io/kezgby/rails-tests) workspace.
P.S. I tried to directly add your email to my workspace but at cloud9 they have no user registered with the above email.

**Comment by davidwessman** [comment]
Please close this issue @knzudgt
