### ISSUE TITLE
Change language of calendar

### ISSUE THREAD

**Issue by elmoaaron** [bokmann/fullcalendar-rails#87]
the option "locale" does not work, the solution  is adding the following line to aplication.js 
//= require fullcalendar/locale-all
maybe you can add it to the readme

**Comment by gr8bit** [comment]
You should also be able to include selected languages by requiring fullcalendar/lang/<lang>... if you are just at it, maybe you could test it and change the readme? Simple PR from the github project mainpage would well be sufficient :)

**Comment by adrianotadao** [comment]
If you want, I can add this and you can review the PR. What do you think?

**Comment by elmoaaron** [comment]
Go ahead ! :)
